spring.application.name=helpdesk
server.port=8080
spring.datasource.url=jdbc:postgresql://10.229.40.177:5432/helpdeskapp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3:8b
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

logging.level.root=debug